# Generated by Django 2.1.5 on 2019-02-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_company_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_login',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company_login',
            name='image',
            field=models.ImageField(blank=True, upload_to='company/%Y/%m/%d'),
        ),
    ]
