# Generated by Django 2.1.5 on 2019-03-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190227_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_login',
            name='upcomming_jobs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='login',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='login',
            name='image',
            field=models.ImageField(blank=True, upload_to='user/%Y/%m/%d'),
        ),
    ]
