# Generated by Django 2.1.5 on 2019-03-02 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190302_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='description',
            new_name='Experince',
        ),
    ]
