# Generated by Django 2.1.5 on 2019-03-12 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190305_2006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='jobseaker_login',
        ),
    ]
