# Generated by Django 2.1.5 on 2019-04-29 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
