# Generated by Django 2.1.5 on 2019-04-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_jobseaker_login_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseaker_login',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
