# Generated by Django 2.1.5 on 2019-04-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_jobseaker_login_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_login',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='jobseaker_login',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
