# Generated by Django 2.1.5 on 2019-04-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20190429_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseaker_login',
            name='gender',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
