# Generated by Django 2.1.5 on 2019-05-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='logi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300, unique=True)),
                ('dob', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
